DunetownShack_MapScripts::
	.byte 0


ShackMan::
	lockall
	faceplayer
	message ShackMan_Text_0
	waitmessage
	releaseall
	end


ShackMan_Text_0:
	.string "The ONE time I finally managed to\p"
	.string "get a girl to come over, she\p"
	.string "said that the way I positioned\p"
	.string "my bed has cursed energy.\p"
	.string "...\p"
	.string "...\p"
	.string "...\p"
	.string "WHAT DOES THAT EVEN MEAN??$"
