TheBricks_MapScripts::
	.byte 0


SamThug::
	lockall
	faceplayer
	msgbox SamThug_Text_0
	releaseall
	end


BricksGirl::
	lockall
	faceplayer
	msgbox BricksGirl_Text_0
	releaseall
	end


BricksKid::
	lockall
	faceplayer
	msgbox BricksKid_Text_0
	releaseall
	end


BricksPooch::
	lockall
	faceplayer
	msgbox BricksPooch_Text_0
	releaseall
	end


BricksZig::
	lockall
	faceplayer
	msgbox BricksZig_Text_0
	releaseall
	end


BricksTrainer::
	lockall
	faceplayer
	msgbox BricksTrainer_Text_0
	releaseall
	end


SamThug_Text_0:
	.string "Come back later, punk.$"

BricksGirl_Text_0:
	.string "It used to be that all of the Bricks\n"
	.string "looked the same. Now there's a nice\l"
	.string "part of town. Not being part of that\l"
	.string "part of town makes me feel worse than\l"
	.string "when we were all just one bad town!$"

BricksKid_Text_0:
	.string "My brother left The Bricks so he could\n"
	.string "work for a company in Shade City! It's\l"
	.string "so far away... I hope I can go there\l"
	.string "someday too.$"

BricksPooch_Text_0:
	.string "Grr...Pooch! Pooch!$"

BricksZig_Text_0:
	.string "Zig! Goon!$"

BricksTrainer_Text_0:
	.string "My Zigzagoon and I walk down from\n"
	.string "Silver City every so often to see what\l"
	.string "we can find on the ground. We make a\l"
	.string "game out of it! I use a metal detector,\l"
	.string "but she still beats me every time!$"
