NewMap4_MapScripts::
	.byte 0


HoneyportLady1::
	lockall
	faceplayer
	msgbox HoneyportLady1_Text_0
	releaseall
	end


HoneyportLady1_Text_0:
	.string "The leaders of Verdeville and Horn\n"
	.string "Hollow are very strong! And they both\l"
	.string "believe strongly in something they call\l"
	.string "the virtue of battle! Don't feel\l"
	.string "discouraged if you can't defeat them\l"
	.string "the first time around, you may just\l"
	.string "need to change up your strategy a bit!$"
