Route13House_MapScripts::
	.byte 0


MrDigital::
	lockall
	faceplayer
	msgbox MrDigital_Text_0
	waitmessage
	releaseall
	end


MrDigitalPoochyena::
	lockall
	faceplayer
	msgbox MrDigitalPoochyena_Text_0
	waitmessage
	releaseall
	end


MrDigital_Text_0:
	.string "My name is Mr. Digital! I moved here from\n"
	.string "Silver City years ago after the hustle\l"
	.string "and bustle got to be too much for me!\l"
	.string "My wife and I were business partners,\l"
	.string "and together founded the company\l"
	.string "that would go on to develop technology\l"
	.string "crucial to the Interface Terminals\l"
	.string "used everywhere in Nova City! But,\l"
	.string "while we agreed that it was time to\l"
	.string "leave it all behind, we didn't agree on\l"
	.string "how to go about it. She disappeared\l"
	.string "during the early explorations into the\l"
	.string "Digital Underworld. It's just me and\l"
	.string "Poochyena now... What I wouldn't give\l"
	.string "to know if she was still out there...$"

MrDigitalPoochyena_Text_0:
	.string "Grr! Chyeh!$"
